### ISSUE TITLE
dua 2.29.0 fails to compile with rustc 1.80.0

### ISSUE THREAD

**Issue by Biswa96** [Byron/dua-cli#253]
* rust version

```
$ rustc --version
rustc 1.80.0
```

* compiler error:

```
error[E0282]: type annotations needed for `Box<_>`
  --> /home/x/cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

The underlying issue has been fixed in time crate 0.3.36 version which was updated in 69a7cdd11068b2e4053460b42d8a4959501a7799 commit.

**Comment by Byron** [comment]
Where is the source code from?

Did you try `cargo update`?

**Comment by Biswa96** [comment]
I downloaded the source tarball from release https://github.com/Byron/dua-cli/archive/refs/tags/v2.29.0.tar.gz and ran `cargo build` in that.

`cargo update` does pull latest time crate 0.3.36 version.

**Comment by Byron** [comment]
Thanks for the information! I understand now what's happening and believe to have fixed it - future releases should not contain the `Cargo.lock` file anymore and automatically build with the latest dependencies.
Retroactively this can't be fixed, so it's as good as it gets.

Closing for that reason, thanks for your understanding.

**Comment by ofalvai** [comment]
@Byron thank you for the fix! Would it be possible to cut a new release containing the fix?
Nixpkgs is tracking the packages broken by Rust 1.80 [here](https://github.com/NixOS/nixpkgs/issues/332957) and the preferred way is to do a version update once there is a release with the fix.

**Comment by Byron** [comment]
No problem at all, here it is: https://github.com/Byron/dua-cli/releases/tag/v2.29.1

**Comment by emilazy** [comment]
Thank you for the rapid fix! I hope you can consider re‐adding the `Cargo.lock` file but just bumping the `time` crate. Having a set of upstream known‐good versions to build against is valuable, it helps the build process with hermetic distributions like Nixpkgs/NixOS, and it can also be useful for suppy‐chain security. The Cargo manual has [some discussion about this](https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control); it used to unambiguously recommend versioning the lock file for an application, though it has some more nuance these days. Generally Cargo has moved in the direction of encouraging versioning more lock files; for instance, in 2023 it [stopped ignoring them by default for even libraries](https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html).

**Comment by emilazy** [comment]
By the way, it looks like it was only actually removed from the GitHub archives, so we could get around this with `forceFetchGit`.

How long until the first supply chain attack that exploits the surprising amount of malleability GitHub archives have…?

**Comment by Byron** [comment]
I think it's all trade-offs and here I'd prefer to get the latest greatest, hoping it will 'make things better rather than worse'. Either way, keeping old versions or using the latest ones, can be the wrong decision, so maybe it helps that I do dependency upgrades and updates only rarely, and somewhat randomly.

**Comment by emilazy** [comment]
An option you might be interested in is using a bot like dependabot to automatically do SemVer‐compatible upgrades to your lock file, and running with `--locked` in CI. You can, I think, even set up dependabot PRs to automatically merge if CI passes. That ensures that the test suite always runs successfully with your locked dependencies, and that they’re always as up to date as possible, while still fixing versions for release tags that can be used for distributions, reproducible builds, and supply chain scanning.

**Comment by Byron** [comment]
Thanks - dependabot indeed seems like an option. Typically I don't set it up as I don't fancy figuring out how its YAML works, while wanting settings that avoid too much noise.
